application: plats
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: welcome.html
  upload: welcome.html
- url: /set_metatag.js
  script: metatag.py
- url: /put_variable.js
  script: variable.py
- url: /style
  static_dir: style 
