application: papershortener
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: frontend.py
- url: /shorten
  script: frontend.py
# - url: /
#   static_files: static/index.html
#  upload: static/index.html
